<div class="product-list">
    <?php
    if (empty($this->items)) :
        ?>
        <div class="product-list__err-msg">Товаров нет</div>
        <?php
    else :    
        foreach ($this->items as $item) : ?>
            <div class="product-list__item">
                <div class="product-list__item-title"><a href="<?php echo $item['link'] ?>"><?php echo $item['name'] ?></a></div>
                <div class="product-list__item-body"><?php echo $item['fieldGroups']['description']['preview'] ?></div>
            </div>
        <?php
        endforeach;
        echo $this->partial('content_template/' . CURRENT_THEME . '/page_nav.phtml');
    endif;    
    ?>
</div>