<?php

$sm = $this->getHelperPluginManager()->getServiceLocator();

?>

<div class="templates-form form-wrap">
    <?php
    $factory = new Zend\Form\Factory($sm->get('FormElementManager'));
    
    $formConfig = $this->formConfig;
   
    $form = $factory->createForm($formConfig);       
    $form->setAttribute('class', 'form-1c');
    $form->setData($this->formValues);    
    
    $form->add(array(
        'type' => 'submit',
        'name' => 'submit',
        'attributes' => array(
            'value' => $this->translate('Submit'),
        ),
    ));
    $form->prepare();
    
    if (!empty($this->formMsg)) {
        $form->setMessages($this->formMsg);
    }
  
    echo $this->form()->openTag($form);
    foreach ($form->getElements() as $el) {
        echo $this->formElementWrapper($el);
    }
    echo $this->form()->closeTag($form);
    ?>
</div>