<?php

$sm = $this->getHelperPluginManager()->getServiceLocator();

?>

<div class="templates-form form-wrap">
    <?php    
    $form = $this->form;
      
    $form->setAttribute('class', 'form-1c');
    
    $form->add(array(
        'type' => 'submit',
        'name' => 'submit',
        'attributes' => array(
            'class' => 'btn',
            'value' => $this->translate('Submit'),
        ),
    ));
    $form->prepare();
    
    if (!empty($this->formMsg)) {
        $form->setMessages($this->formMsg);
    }
  
    echo $this->form()->openTag($form);
    foreach ($form->getElements() as $el) {
        echo $this->formElementWrapper($el);
    }
    echo $this->form()->closeTag($form);
    ?>
</div>