<?php

if (!$this->allowRegistration) {
    print "Registration is disabled";
    return;
}

$form = $this->form;
$form->prepare();

?>
<div class="registration__wrap">
    <div class="registration">
        <?php
        echo $this->form()->openTag($form);  
        ?>
        <input type="hidden" name="task" value="register" />
        <?php
        foreach ($form->getFieldsets() as $fieldset) :     
            ?>
            <div class="block">
                <div class="block__title"><?php echo $fieldset->getLabel() ?></div>
                <div class="block__body">
                    <?php           
                    foreach ($fieldset->getElements() as $el) :
                        echo $this->formElementWrapper($el);
                    endforeach;
                    ?>
                </div>
            </div>
            <?php
        endforeach;    
        ?>    
        <div class="block__buttons">
            <input type="submit" name="submit" id="submit" value="Зарегистрироваться">
        </div>
        <?php echo $this->form()->closeTag($form); ?>
    </div>
</div>