<?php

$this->inlineScript()->appendFile(ROOT_URL_SEGMENT . '/js/Users/users.js');

$data = array(
    'createBtn' => array(
        'text' => 'Добавить пользователя',
        'link' => $this->url('admin/method', array(
            'module' => 'Users',
            'method' => 'AddUser',
        )),
    ),
    'url' => $this->url('admin/UsersList', array(
        'task'   => 'get_data',
    )),  
    'columns' => array(
        array(
            array(                        
                'title' => $this->translate('Users:Name field'),
                'field' => 'name',
                'width' => '200',
            ),
            array(                        
                'title' => '',
                'field' => 'icons',
                'width' => '200',
            )
        )                    
    ),
);

echo $this->partial('content_template/' . CURRENT_THEME . '/tree_grid.phtml', $data);