<?php

$fieldsets = $this->form->getFieldsets();
if (empty($fieldsets)) :
    ?>
    <div class="dynamic-config__msg"><?php echo $this->translate('Dynamic config no config in this tab') ?></div>
    <?php
    return;
endif;

?>
<div class="dynamic-config form-3c-wrap">
    <?php
    
    $form = $this->form;
    $form->setAttribute('class', 'form-3c');
    $form->prepare();
    
    echo $this->form()->openTag($form);
    ?>
    <?php
    
    foreach ($form->getFieldsets() as $fieldset) :   
        if ($fieldset->getLabel()) :
            ?>
            <fieldset><legend><?php echo $fieldset->getLabel() ?></legend>
            <?php
        endif;
        foreach ($fieldset->getFieldsets() as $subFieldset) {
            echo $this->formCollection3C($subFieldset);
        }
        foreach ($fieldset->getElements() as $el) :
            echo $this->formElementWrapper3C($el);
        endforeach;
        if ($fieldset->getLabel()) :
            ?>
            </fieldset>    
            <?php
        endif;
    endforeach;
    ?>
    <div class="form-3c-element form-element__submit">
        <input type="submit" value="<?php echo $this->translate('Save button') ?>" />
    </div>
    <?php echo $this->form()->closeTag($form); ?>
</div>
