<?php

$fieldsets = $this->form->getFieldsets();
if (empty($fieldsets)) :
    ?>
    <div class="dynamic-config__msg"><?php echo $this->translate('Dynamic config no config in this tab') ?></div>
    <?php
    return;
endif;

?>
<div class="dynamic-config form-3c-wrap">
    <?php
    
    $form = $this->form;
    $form->setAttribute('class', 'form-3c');
    $form->prepare();
    
    echo $this->form()->openTag($form);
    
    echo $this->formCollection3C($form);
    ?>
    <div class="form-3c-element form-element__submit">
        <input class="btn" type="submit" value="<?php echo $this->translate('Save button') ?>" />
    </div>
    <?php echo $this->form()->closeTag($form); ?>
</div>
