<?php

$form = $this->form;   
$form->prepare();

if (isset($this->formMsg)) {
    $form->setMessages($this->formMsg);
}

?>
<div class="login_form">
    <?php echo $this->form()->openTag($form) ?>
    <div class="b-login_form__wrapper">                
        <div class="b-login_form">  
            <?php echo $this->formElementErrors($form->get('identity')) ?>
            <div class="b-login_form__login_div">                         
                <div><?php echo $this->formLabel($form->get('identity')) ?></div>
                <div><?php echo $this->formInput($form->get('identity')) ?></div>
            </div>
            <div class="b-login_form__pass_div">
                <div><?php echo $this->formLabel($form->get('credential')) ?></div>
                <div><?php echo $this->formInput($form->get('credential')) ?></div>
            </div>
            <input type="hidden" name="remember_me" value="1" />
            <input type="hidden" name="task" value="login" />
            <?php if ($this->redirect): ?>
                <input type="hidden" name="redirect" value="<?php echo $this->redirect ?>" />
            <?php endif ?>
            <div class="b-login_form__sbmt_div">
                <input type="submit" name="submit" id="submit" value="<?php echo $this->translate('Users:Login btn') ?>">
            </div>
            <?php if ($this->allowRegistration) : ?>
            <div class="b-login_form__register_div">
                <a href="<?php echo $this->url('register', array(), $this->redirect ? array('query' => array('redirect' => $this->redirect)) : array()) ?>"><?php echo $this->translate('Users: Sign up') ?></a>
            </div>
            <?php endif; ?>
            <?php if ($this->loginza) : ?>
            <script src="http://loginza.ru/js/widget.js" type="text/javascript"></script>
            <div class="b-login_form__loginza_div">
                <a href="http://loginza.ru/api/widget?token_url=<?php echo $this->serverUrl() . $this->url('loginza', array(), $this->redirect ? array('query' => array('redirect' => $this->redirect)) : array()) ?>" class="loginza">
                    <img src="http://loginza.ru/img/sign_in_button_gray.gif" alt="Войти через loginza"/>
                </a>                    
            </div>
            <?php endif; ?>
        </div>            
    </div>
    <?php echo $this->form()->closeTag() ?>
</div>