<?php

$sm = $this->getHelperPluginManager()->getServiceLocator();

$factory = new Zend\Form\Factory($sm->get('FormElementManager'));
$formConfig = $this->formConfig;

$form = $factory->createForm($formConfig);   
$form->setAttribute('method', 'post');
$form->setData($this->formValues);
$form->prepare();

if (isset($this->formMsg)) {
    $form->setMessages($this->formMsg);
}

?>
<div class="login_form">
    <?php echo $this->form()->openTag($form) ?>
    <div class="b-login_form__wrapper">                
        <div class="b-login_form">  
            <?php echo $this->formElementErrors($form->get('identity')) ?>
            <div class="b-login_form__login_div">                         
                <div><?php echo $this->formLabel($form->get('identity')) ?></div>
                <div><?php echo $this->formInput($form->get('identity')) ?></div>
            </div>
            <div class="b-login_form__pass_div">
                <div><?php echo $this->formLabel($form->get('credential')) ?></div>
                <div><?php echo $this->formInput($form->get('credential')) ?></div>
            </div>
            <?php if ($this->redirect): ?>
                <input type="hidden" name="redirect" value="<?php echo $this->redirect ?>" />
            <?php endif ?>
            <div class="b-login_form__sbmt_div">
                <input type="submit" name="submit" id="submit" value="<?php echo $this->translate('Users:Login btn') ?>">
            </div>
            <?php if ($this->enableRegistration) : ?>
            <div class="b-login_form__register_div">
                <a href="<?php echo $this->url('register') ?>"><?php echo $this->translate('Users: Sign up') ?></a>
            </div>
            <?php endif; ?>
        </div>            
    </div>
    <?php echo $this->form()->closeTag() ?>
</div>