<?php

$sm = $this->getHelperPluginManager()->getServiceLocator();

?>

<div class="blocks">
    <?php
    $factory = new Zend\Form\Factory($sm->get('FormElementManager'));
    $formConfig = $this->formConfig;
    
    $form = $factory->createForm($formConfig);       
    $form->setAttribute('class', 'form-2c');
    $form->setData($this->formValues);
    $form->prepare();
    
    if (isset($this->formMsg)) {
        $form->setMessages($this->formMsg);
    }
    
    echo $this->form()->openTag($form);  
    ?>
    <div class="block">
        <div class="block__title"> </div>
        <div class="block__body">
            <?php           
            foreach ($form->getElements() as $el) :
                echo $this->formElementWrapper($el);
            endforeach;
            ?>
        </div>
    </div>
    <div class="block__buttons block__buttons-left clearfix">
        <dd><input type="submit" name="submit" id="submit" value="Сохранить"></dd>
    </div>
    <?php echo $this->form()->closeTag($form); ?>
</div>    
