<?php

$this->inlineScript()->appendFile(ROOT_URL_SEGMENT . '/js/Rbac/roles.js');

$data = array(
    'createBtn' => array(
        'text' => 'Добавить роль',
        'link' => $this->url('admin/method', array(
            'module' => 'Rbac',
            'method' => 'AddRole',
        )),
    ),
    'url' => $this->url('admin/RolesList', array(
        'task'   => 'get_data',
    )),  
    'columns' => array(
        array(
            array(                        
                'title' => $this->translate('Rbac:Name field'),
                'field' => 'name',
                'width' => '200',
            ),
            array(                        
                'title' => '',
                'field' => 'icons',
                'width' => '200',
            )
        )                    
    ),      
);

echo $this->partial('content_template/AdminPanel/tree_grid.phtml', $data);