<?php
if (isset($this->errMsg)) :
?>
<div class="news-item">
    <div class="news-item__err-msg"><?php echo $this->errMsg; ?></div>
</div>
<?php
endif;

if (!$this->success)
    return;
?>
<div class="product-item">
    <div class="product-item__title"><?php echo $this->name ?></div>
    <div class="product-item__body"><?php echo $this->fieldGroups['description']['full_description'] ?></div>
</div>