<?php

$this->headTitle()->setSeparator(' - ');
$this->headTitle('Zen-CMS');
$this->headTitle($this->translate('Users:Authorization'));

$this->headLink(array('rel' => 'icon', 'href' => ROOT_URL_SEGMENT . '/img/Users/favicon.ico'));   

$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');

if (!$this->enableRegistration) {
    print "Registration is disabled";
    return;
}

$form = $this->form;
$form->prepare();

$this->headLink()->appendStylesheet(ROOT_URL_SEGMENT . '/css/Users/registration.css');

?>
<div class="registration__wrap">
    <div class="registration">
        <?php
        echo $this->form()->openTag($form);  
        foreach ($form->getFieldsets() as $fieldset) :     
            ?>
            <div class="block">
                <div class="block__title"><?php echo $fieldset->getLabel() ?></div>
                <div class="block__body">
                    <?php           
                    foreach ($fieldset->getElements() as $el) :
                        echo $this->formElementWrapper($el);
                    endforeach;
                    ?>
                </div>
            </div>
            <?php
        endforeach;    
        ?>    
        <div class="block__buttons">
            <input type="submit" name="submit" id="submit" value="Зарегистрироваться">
        </div>
        <?php echo $this->form()->closeTag($form); ?>
    </div>
</div>