<div class="steps clearfix">
    <div class="steps__item<?php echo ($this->currentStep == 1) ? ' steps__item-act' : '' ?>">
        1. <?php echo $this->translate('Installer choose language') ?>
    </div>
    <div class="steps__item<?php echo ($this->currentStep == 2) ? ' steps__item-act' : '' ?>">
        2. <?php echo $this->translate('Installer DB settings') ?>
    </div>
    <div class="steps__item<?php echo ($this->currentStep == 3) ? ' steps__item-act' : '' ?>">
        3. <?php echo $this->translate('Installer check server') ?>
    </div>
    <div class="steps__item<?php echo ($this->currentStep == 4) ? ' steps__item-act' : '' ?>">
        4. <?php echo $this->translate('Installer install system') ?>
    </div>
    <div class="steps__item<?php echo ($this->currentStep == 5) ? ' steps__item-act' : '' ?>">
        5. <?php echo $this->translate('Installer install demo site') ?>
    </div>
    <div class="steps__item<?php echo ($this->currentStep == 6) ? ' steps__item-act' : '' ?>">
        6. <?php echo $this->translate('Installer access settings') ?>
    </div>
</div>