<?php
$bodyAttrStr = '';
if (!empty($this->bodyAttr)) {    
    foreach ($this->bodyAttr as $k=>$v) {
        $bodyAttrStr .= ' ' . $k . '="' . $v . '"';
    }
}

echo $this->doctype(); ?> 
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
	<head>
		<?php echo $this->headTitle() ?>
		<?php echo $this->headMeta() ?>
		<?php echo $this->headLink() ?>
		<?php echo $this->headStyle() ?>
		<?php echo $this->headScript() ?>	
	</head>    
    <body<?php echo $bodyAttrStr ?>>
    <?php echo $this->content ?>
    <?php echo $this->inlineScript() ?>
    </body>
</html>