<?php
    $this->headLink()->appendStylesheet($this->basePath('/css/core/404.css'));
    $this->headLink(array('rel' => 'icon', 'href' => ROOT_URL_SEGMENT . '/img/core/favicon.ico'));   
    
    $this->headTitle()->setSeparator(' - ');
    $this->headTitle('Zen-CMS');
    $this->headTitle($this->translate('core:Page not found'));
    
    $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8');
?>
<img src="<?php echo $this->basePath('/img/core/404.png') ?>" />