<?php
    $this->headLink()->getContainer()->exchangeArray(array());
    $this->headScript()->getContainer()->exchangeArray(array());
    $this->inlineScript()->getContainer()->exchangeArray(array());

    $this->headLink()->appendStylesheet($this->basePath('/css/core/404.css'));
    $this->headLink(array('rel' => 'icon', 'href' => $this->basePath('/img/core/favicon.ico')));   
    
    $this->headTitle()->setSeparator(' - ');
    $this->headTitle('Zen-CMS');
    $this->headTitle($this->translate('core:Page not found'));
    
    $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8');
?>
<img src="<?php echo $this->basePath('/img/core/404.png') ?>" />