<?php

$this->inlineScript()->appendFile(ROOT_URL_SEGMENT . '/js/Pages/pages.js');

if ('edit' == $this->task) {
    $args = array(
        'changeContentTypeUrl' => $this->url('admin/EditContent', array(
            'id' => $this->contentId,
            'pageContentTypeId' => '--CONTENT_TYPE--',
        )), 
        'changeObjectTypeUrl' => $this->url('admin/EditContent', array(
            'id' => $this->contentId,
            'pageContentTypeId' => '--CONTENT_TYPE--',
            'objectTypeId' => '--OBJECT_TYPE--',
        )),
    );
    
    $this->inlineScript()->appendScript('zen.pages.initContentEdit(' . json_encode($args) . ');');    
} elseif ('add' == $this->task) {    
    $args = array(
        'changeContentTypeUrl' => $this->url('admin/AddContent', array(
            'markerId' => $this->markerId,
            'beforeContentId' => $this->beforeContentId,
            'pageId' => $this->pageId,
            'pageContentTypeId' => '--CONTENT_TYPE--',
        )), 
        'changeObjectTypeUrl' => $this->url('admin/AddContent', array(
            'markerId' => $this->markerId,
            'beforeContentId' => $this->beforeContentId,
            'pageId' => $this->pageId,
            'pageContentTypeId' => '--CONTENT_TYPE--',
            'objectTypeId' => '--OBJECT_TYPE--',
        )),
    );
    
    $this->inlineScript()->appendScript('zen.pages.initContentEdit(' . json_encode($args) . ');');    
}

?>

<div class="blocks blocks__page">
    <?php
    
    $form = $this->form;       
    $form->setAttribute('class', 'form-2c');
    $form->prepare();
        
    echo $this->form()->openTag($form);
    foreach ($form->getFieldsets() as $fieldset) :     
        ?>
        <div class="block">
            <div class="block__title"><?php echo $fieldset->getLabel() ?></div>
            <div class="block__body">
                <?php           
                foreach ($fieldset->getElements() as $el) :
                    echo $this->formElementWrapper($el);
                endforeach;
                ?>
            </div>
        </div>
        <?php
    endforeach;
    ?>
    <div class="block__buttons block__buttons-left clearfix">
        <dd><input type="submit" name="submit" id="submit" value="Сохранить"></dd>
    </div>
    <?php echo $this->form()->closeTag($form); ?>
</div>    
