<?php

$this->inlineScript()->appendFile(ROOT_URL_SEGMENT . '/js/Pages/pages.js');

$data = array(
    'url' => $this->url('admin/PagesList', array(
        'task'   => 'get_data',
    )),  
    'columns' => array(
        array(
            array(                        
                'title' => $this->translate('Pages:Page name field'),
                'field' => 'name',
                'width' => '200',
            ),
            array(                        
                'title' => '',
                'field' => 'icons',
                'width' => '200',
            )
        )                    
    ),
);

echo $this->partial('content_template/' . CURRENT_THEME . '/tree_grid.phtml', $data);