<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'elFinderConnector'             => __DIR__ . '/src/Library/elFinderConnector.class.php',
    'elFinder'                      => __DIR__ . '/src/Library/elFinder.class.php',
    'elFinderVolumeDriver'          => __DIR__ . '/src/Library/elFinderVolumeDriver.class.php',
    'elFinderVolumeLocalFileSystem' => __DIR__ . '/src/Library/elFinderVolumeLocalFileSystem.class.php',
);
