<?php
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Zen-CMS');
$this->headTitle('Административная панель');
$this->headTitle($this->page['title']);
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headMeta()->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headLink(array('rel' => 'icon', 'href' => ROOT_URL_SEGMENT . '/img/ChameleonTheme/favicon.ico'));

$this->headLink(array('rel' => 'canonical', 'href' => $this->page['canonicalUrl']));


$sm = $this->getHelperPluginManager()->getServiceLocator();

//$layout = $this->layout();

$this->headScript()->prependFile($this->basePath('/js/core/modernizr.js'));

$this->inlineScript()->prependScript('zen.bootstrapTheme.init({baseUrl: "' . $this->basePath() . '"});')
    ->prependFile($this->basePath('/js/core/jquery_plugins/fancybox/jquery.fancybox.pack.js'))
    ->prependFile($this->basePath('/js/core/jquery_plugins/jquery-toastmessage-plugin/javascript/jquery.toastmessage.js'))
    ->prependFile($this->basePath('/js/core/jquery_plugins/jquery.alerts-1.1/jquery.alerts.js'))
    ->prependFile($this->basePath('/js/core/jquery_ui/jquery-ui-1.9.2/js/jquery-ui-1.9.2.custom.min.js'))
    ->prependFile($this->basePath('/js/core/jquery-easyui-1.3.4/locale/easyui-lang-ru.js'))
    ->prependFile($this->basePath('/js/core/jquery-easyui-1.3.4/jquery.easyui.min.js'))
    ->prependFile($this->basePath('/js/BootstrapTheme/bootstrap_theme.js'))
    ->prependFile($this->basePath('/tools/core/bootstrap/js/bootstrap.min.js'))
    ->prependFile($this->basePath('/js/core/zen_base.js'))
    ->prependFile($this->basePath('/js/core/jquery_plugins/jquery.form.js'))
    ->prependFile($this->basePath('/js/core/backbone-min.js'))
    ->prependFile($this->basePath('/js/core/underscore-min.js'))
    ->prependScript('window.jQuery || document.write(\'<script src="' . $this->basePath('/js/core/jquery/jquery-1.10.2.min.js') . '"><\/script>\')')
    ->prependFile('//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js');



$this->headLink()->prependStylesheet($this->basePath('/js/core/jquery_plugins/fancybox/jquery.fancybox.css'))
    ->prependStylesheet($this->basePath('/js/core/jquery_plugins/jquery-toastmessage-plugin/resources/css/jquery.toastmessage.css'))
    ->prependStylesheet($this->basePath('/js/core/jquery_plugins/jquery.alerts-1.1/jquery.alerts.css'))
    ->prependStylesheet($this->basePath('/css/BootstrapTheme/main.css'))
    ->prependStylesheet($this->basePath('/tools/core/bootstrap/css/bootstrap.min.css'))
    ->prependStylesheet($this->basePath('/js/core/jquery_ui/jquery-ui-1.9.2/css/smoothness/jquery-ui-1.9.2.custom.min.css'))
    ->prependStylesheet($this->basePath('/js/core/jquery-easyui-1.3.4/themes/metro/easyui.css'));
?>
<?php
if (isset($this->errors)) {
    echo $this->partial('content_template/core/errors.phtml', $this->errors);
}
?>
<div id="loading-msg" class="loading-msg"><?php echo $this->translate('Loading') ?></div>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <div class="row">
                <a class="pull-left brand" href="<?php echo $this->url('admin') ?>">Zen-CMS</a>
                <div class="pull-right"><?php echo $this->partial('content_template/BootstrapTheme/login_block.phtml', $this->user); ?></div>
            </div>   
            <?php echo $this->executeMethod('AdminPanel\Method\AdminMainMenu', array(), 'content_template/BootstrapTheme/main_menu.phtml'); ?>
            
        </div>
    </div>
</div>
<div class="container">	
    <?php echo $this->partial('content_template/BootstrapTheme/breadcrumbs.phtml'); ?>
    <?php echo $this->partial('content_template/BootstrapTheme/content.phtml', $this->page); ?>    
    <hr />
    <footer class="footer">
        <?php echo $this->partial('content_template/BootstrapTheme/page_info.phtml', $this->systemInfo); ?>
        <br />
    </footer>
</div>