<?php
$this->headLink()->appendStylesheet($this->basePath('/css/Installer/install.css'));
$this->headLink(array('rel' => 'icon', 'href' => $this->basePath('/img/Installer/favicon.ico')));

$this->headTitle()->setSeparator(' - ');
$this->headTitle('Zen-CMS');
$this->headTitle($this->translate('Installer:System installation'));
$this->headTitle($this->translate('Installer:Complete step'));

$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8');
$sm = $this->getHelperPluginManager()->getServiceLocator();
?>
<div class="container">
    <div class="header clearfix">	
        <img alt="Chameleon CMS" style="background-color: rgb(136, 136, 136)" src="<?php echo $this->basePath('/img/core/pixel.gif') ?>" class="logo" id="logo">
    </div>
    <div class="content">
        <?php
        if (!empty($this->msg)) :
            ?>
            <div class="content__msg">
                <?php foreach ($this->msg as $msg) : ?>
                <div class="content__msg-item"><?php echo $msg ?></div>
                <?php endforeach; ?>
            </div>
            <?php
        endif;
        ?>
        <div class="content__body form-wrap">
            <div class="install-complete">
                <div class="install-complete__inside">
                    <div class="install-complete__msg"><?php printf($this->translate('Installer install complete msg %s'), $this->basePath('/admin/')) ?></div>
                </div>
            </div>
        </div>
    </div>
</div>