<?php
$this->headLink()->appendStylesheet($this->basePath('/css/Installer/install.css'));
$this->headLink(array('rel' => 'icon', 'href' => $this->basePath('/img/Installer/favicon.ico')));

$this->headTitle()->setSeparator(' - ');
$this->headTitle('Zen-CMS');
$this->headTitle($this->translate('Installer:System installation'));
$this->headTitle($this->translate('Installer:Step 4'));

$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8');
$sm = $this->getHelperPluginManager()->getServiceLocator();
?>
<div class="container">
    <div class="header clearfix">	
        <img alt="Chameleon CMS" style="background-color: rgb(136, 136, 136)" src="<?php echo $this->basePath('/img/core/pixel.gif') ?>" class="logo" id="logo">
    </div>
    <?php echo $this->partial('content_template/Installer/steps.phtml', array('currentStep' => 4)); ?>
    <div class="content">
        <div class="content__title"><?php echo $this->translate('Installer install system') ?></div>
        <?php
        if (!empty($this->msg)) :
            ?>
            <div class="content__msg">
                <?php foreach ($this->msg as $msg) : ?>
                <div class="content__msg-item"><?php echo $msg ?></div>
                <?php endforeach; ?>
            </div>
            <?php
        endif;
        ?>
        <div class="content__body form-wrap">
            <?php            
            if (isset($this->installResult)) :
                if ($this->installResult) :
                    ?>
                    <div class="install-system-msg"><?php echo $this->translate('Installer system installed successfull') ?></div>   
                    <div class="form-element form-element__submit">
                        <form method="post">
                            <input type="submit" value="<?php echo $this->translate('Installer next button') ?>" />
                        </form>
                    </div>
                    <?php
                else :
                    ?>
                    <div class="install-system-msg"><?php echo $this->translate('Installer system installed fail') ?></div>   
                    <div class="form-element form-element__submit">
                        <form method="post">
                            <input type="submit" value="<?php echo $this->translate('Installer refresh button') ?>" />
                        </form>
                    </div>
                    <?php
                endif;
            else :
                ?>
                <div class="install-system-msg"><?php echo $this->translate('Installer system ready to install') ?></div>
                <div class="form-element form-element__submit">
                    <form method="post">
                        <input type="submit" value="<?php echo $this->translate('Installer next button') ?>" />
                    </form>    
                </div>
                <?php
            endif;            
            ?>            
        </div>
    </div>
</div>