<?php

return array(
    'Chameleon theme module' => 'Тема "Хамелеон"',
    'Chameleon theme module description' => 'Тема для административной панели "Хамелеон"',
    
	'Welcome to zen-cms!' => 'Добро пожаловать в Zen-CMS!',
    'List of active modules:' => 'Список активных модулей:',
    'Methods' => 'Методы',
    
    'This page was generated by %g seconds' => 'Страницы сгенерирована за %g секунды',
    'Max memory %g kb' => 'Затрачено памяти: %g кбайт',
    'Queries executed: %d' => 'Выполнено запросов: %d',
    'Included files: %d' => 'Подключено файлов: %d',
    
    'Logout' => 'Выйти',
);