<?php
    $this->headLink()->getContainer()->exchangeArray(array());
    $this->headScript()->getContainer()->exchangeArray(array());
    $this->inlineScript()->getContainer()->exchangeArray(array());

    $this->headTitle()->setSeparator(' - ');
    $this->headTitle('Zen-CMS');
    $this->headTitle($this->translate('Rbac:Access forbidden'));
    
    $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
    $this->headLink(array('rel' => 'icon', 'href' => ROOT_URL_SEGMENT . '/img/Rbac/favicon.ico'));   
    
    $this->headLink()->appendStylesheet($this->basePath('/css/Rbac/403.css'));
?>
<img src="<?php echo $this->basePath('/img/Rbac/403.jpg') ?>" alt="Access denied" />